### ISSUE TITLE
Examples not working in OSX

### ISSUE THREAD

**Issue by gizmomogwai** [tanitta/armos#10]
Every example gives me: 

DerelictGL3.reload failure: An OpenGL context is not currently active.

Tested version was: 3a91f38d9c193a5dc5af85506c173ae313119a84

**Comment by tanitta** [comment]
I will try to research into the problem. But, this probably takes a long time because of having no my OSX computer... 

Thank you for your report :)

**Comment by tanitta** [comment]
By some change, enable to work on my computer(on MacBook Pro late2016):tada:

I’m worried about others...
